### ISSUE TITLE
Base User System?

### ISSUE THREAD

**Issue by benfalk** [three-triangles/ganondorf#1]
Should we use a system like [Addict](https://github.com/trenpixster/addict) to handle the user authentication?  Hand roll our own?  Use a plugin-like system that would allow us to drop in Addict or any other system?

**Comment by niftyn8** [comment]
@benfalk personally I'd recommend just starting with the token stuff and ignoring user consent for now...

**Comment by benfalk** [comment]
@niftyn8 I am totally fine working on only tackling the _specific_ part of the spec that openid connect describes.  My only concern is it having a big hole for the part that is left up to implementation to solve, which is authentication.  For now would it be cool then that we just solve the parts of the spec it specifies then put in `callbacks` for the parts that something like Addict solves in terms of authentication of users?  @edubkendo what say you?

**Comment by edubkendo** [comment]
looks like doorkeeper does something like what you describe: https://github.com/doorkeeper-gem/doorkeeper#authenticating
